// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsMessages(lhsKey, rhsKey) {
          if deepEqualsMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum VpnStatus: Int {
  case disconnecting = 0
  case disconnected = 1
  case connecting = 2
  case connected = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct AndroidAppInfo: Hashable {
  var name: String
  var packageName: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AndroidAppInfo? {
    let name = pigeonVar_list[0] as! String
    let packageName = pigeonVar_list[1] as! String

    return AndroidAppInfo(
      name: name,
      packageName: packageName
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      packageName,
    ]
  }
  static func == (lhs: AndroidAppInfo, rhs: AndroidAppInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.name, rhs.name) && deepEqualsMessages(lhs.packageName, rhs.packageName)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AndroidAppInfo")
    deepHashMessages(value: name, hasher: &hasher)
    deepHashMessages(value: packageName, hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VpnStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return AndroidAppInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? VpnStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? AndroidAppInfo {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BridgeHostApi {
  func getTunFilesDir(completion: @escaping (Result<String, Error>) -> Void)
  func readVpnStatus(completion: @escaping (Result<Void, Error>) -> Void)
  func startVpn(completion: @escaping (Result<Void, Error>) -> Void)
  func stopVpn(completion: @escaping (Result<Void, Error>) -> Void)
  func getFreePorts(num: Int64, completion: @escaping (Result<String, Error>) -> Void)
  func convertShareLinksToXrayJson(base64Text: String, completion: @escaping (Result<String, Error>) -> Void)
  func convertXrayJsonToShareLinks(base64Text: String, completion: @escaping (Result<String, Error>) -> Void)
  func countGeoData(base64Text: String, completion: @escaping (Result<String, Error>) -> Void)
  func readGeoFiles(base64Text: String, completion: @escaping (Result<String, Error>) -> Void)
  func ping(base64Text: String, completion: @escaping (Result<String, Error>) -> Void)
  func testXray(base64Text: String, completion: @escaping (Result<String, Error>) -> Void)
  func runXray(base64Text: String, completion: @escaping (Result<String, Error>) -> Void)
  func stopXray(completion: @escaping (Result<String, Error>) -> Void)
  func xrayVersion(completion: @escaping (Result<String, Error>) -> Void)
  func checkVpnPermission(completion: @escaping (Result<Bool, Error>) -> Void)
  func getInstalledApps(completion: @escaping (Result<[AndroidAppInfo], Error>) -> Void)
  func useSystemExtension(completion: @escaping (Result<Bool, Error>) -> Void)
  func setAppIcon(appIcon: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func getCurrentAppIcon(completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BridgeHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `BridgeHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BridgeHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getTunFilesDirChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.getTunFilesDir\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getTunFilesDirChannel.setMessageHandler { _, reply in
        api.getTunFilesDir { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getTunFilesDirChannel.setMessageHandler(nil)
    }
    let readVpnStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.readVpnStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readVpnStatusChannel.setMessageHandler { _, reply in
        api.readVpnStatus { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readVpnStatusChannel.setMessageHandler(nil)
    }
    let startVpnChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.startVpn\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startVpnChannel.setMessageHandler { _, reply in
        api.startVpn { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startVpnChannel.setMessageHandler(nil)
    }
    let stopVpnChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.stopVpn\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopVpnChannel.setMessageHandler { _, reply in
        api.stopVpn { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopVpnChannel.setMessageHandler(nil)
    }
    let getFreePortsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.getFreePorts\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getFreePortsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let numArg = args[0] as! Int64
        api.getFreePorts(num: numArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getFreePortsChannel.setMessageHandler(nil)
    }
    let convertShareLinksToXrayJsonChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.convertShareLinksToXrayJson\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      convertShareLinksToXrayJsonChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let base64TextArg = args[0] as! String
        api.convertShareLinksToXrayJson(base64Text: base64TextArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      convertShareLinksToXrayJsonChannel.setMessageHandler(nil)
    }
    let convertXrayJsonToShareLinksChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.convertXrayJsonToShareLinks\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      convertXrayJsonToShareLinksChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let base64TextArg = args[0] as! String
        api.convertXrayJsonToShareLinks(base64Text: base64TextArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      convertXrayJsonToShareLinksChannel.setMessageHandler(nil)
    }
    let countGeoDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.countGeoData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      countGeoDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let base64TextArg = args[0] as! String
        api.countGeoData(base64Text: base64TextArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      countGeoDataChannel.setMessageHandler(nil)
    }
    let readGeoFilesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.readGeoFiles\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readGeoFilesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let base64TextArg = args[0] as! String
        api.readGeoFiles(base64Text: base64TextArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readGeoFilesChannel.setMessageHandler(nil)
    }
    let pingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.ping\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let base64TextArg = args[0] as! String
        api.ping(base64Text: base64TextArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pingChannel.setMessageHandler(nil)
    }
    let testXrayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.testXray\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      testXrayChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let base64TextArg = args[0] as! String
        api.testXray(base64Text: base64TextArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      testXrayChannel.setMessageHandler(nil)
    }
    let runXrayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.runXray\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      runXrayChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let base64TextArg = args[0] as! String
        api.runXray(base64Text: base64TextArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      runXrayChannel.setMessageHandler(nil)
    }
    let stopXrayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.stopXray\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopXrayChannel.setMessageHandler { _, reply in
        api.stopXray { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopXrayChannel.setMessageHandler(nil)
    }
    let xrayVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.xrayVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      xrayVersionChannel.setMessageHandler { _, reply in
        api.xrayVersion { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      xrayVersionChannel.setMessageHandler(nil)
    }
    let checkVpnPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.checkVpnPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkVpnPermissionChannel.setMessageHandler { _, reply in
        api.checkVpnPermission { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkVpnPermissionChannel.setMessageHandler(nil)
    }
    let getInstalledAppsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.getInstalledApps\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getInstalledAppsChannel.setMessageHandler { _, reply in
        api.getInstalledApps { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getInstalledAppsChannel.setMessageHandler(nil)
    }
    let useSystemExtensionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.useSystemExtension\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      useSystemExtensionChannel.setMessageHandler { _, reply in
        api.useSystemExtension { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      useSystemExtensionChannel.setMessageHandler(nil)
    }
    let setAppIconChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.setAppIcon\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAppIconChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appIconArg = args[0] as! String
        api.setAppIcon(appIcon: appIconArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setAppIconChannel.setMessageHandler(nil)
    }
    let getCurrentAppIconChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colitu.BridgeHostApi.getCurrentAppIcon\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCurrentAppIconChannel.setMessageHandler { _, reply in
        api.getCurrentAppIcon { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCurrentAppIconChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol BridgeFlutterApiProtocol {
  func vpnStatusChanged(status statusArg: VpnStatus, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class BridgeFlutterApi: BridgeFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func vpnStatusChanged(status statusArg: VpnStatus, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.colitu.BridgeFlutterApi.vpnStatusChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
